[build]
rustflags = ["-Wclippy::all", "-Wclippy::pedantic", "-Wclippy::nursery", "-Wclippy::perf"]

[alias]
check-all = "clippy -- -Dwarnings"
fix-all = "clippy --fix -- -Dwarnings"

# Configure Rust version for stable numeric algorithms
[target.'cfg(not(debug_assertions))']
rustflags = ["-C", "target-cpu=native", "-C", "opt-level=3"]
